version: 2
jobs:
  build-job:
    machine: 
        enabled: true

    steps:
      - checkout
      
      - run: docker login nvcr.io -u \$oauthtoken -p $NVIDIA_DOCKER_OAUTH_KEY
      - run: docker pull nvcr.io/nvidia/tensorflow:18.08-py3
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -t $DOCKER_ORGANIZATION/$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH .
      - run: docker push $DOCKER_ORGANIZATION/$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH && sleep 10

      - store_artifacts:
          path: Dockerfile

  test-job:
    docker:
      - image: $DOCKER_ORGANIZATION/$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH
          
    steps:
      - checkout

      - run:
          name: start Xvfb for phantomjs test
          command: Xvfb :99
          background: true

      - run:
          name: bats tests
          command: |
            mkdir -p test_results/bats
            bats scripts/tests.bats | \
            perl scripts/tap-to-junit.sh > \
            test_results/bats/results.xml

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results
          
  deploy-job:
    docker:
      - image: $DOCKER_ORGANIZATION/$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH
          
    steps:
      - checkout
      
workflows:
  version: 2
    build-test-deploy:
      jobs:
        - build-job:
            context: DOCKER_HUB
        - test-job:
            context: DOCKER_HUB
            requires:
              - build-job
        - deploy-job:
            context: DOCKER_HUB
            requires:
              - test-job
            branches:
              only:
                - master

