version: 2
jobs:
  build:
    machine: 
      docker_layer_caching: true

    steps:
      - checkout
      - run: docker login nvcr.io -u \$oauthtoken -p $NVIDIA_DOCKER_OAUTH_KEY
      - run: docker pull nvcr.io/nvidia/tensorflow:18.08-py3
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker build -t $DOCKER_ORGANIZATION/$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH .
      - run: docker push $DOCKER_ORGANIZATION/$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH && sleep 10

      - store_artifacts:
          path: Dockerfile

  test:
    docker:
      - image: $DOCKER_ORGANIZATION/$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH

      - setup_remote_docker:
          docker_layer_caching: true
                    
    steps:
      - checkout

      - run:
          name: start Xvfb for phantomjs test
          command: Xvfb :99
          background: true

      - run:
          name: bats tests
          command: |
            mkdir -p test_results/bats
            bats scripts/tests.bats | \
            perl scripts/tap-to-junit.sh > \
            test_results/bats/results.xml

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results
      
workflows:
  version: 2
  build_test:
    jobs:
      - build:
          context: DOCKER_HUB
      - test:
          context: DOCKER_HUB
          requires:
            - build


